name: Playwright Tests

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}

      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        if: always()
        run: |
          npx allure generate allure-results --clean -o allure-report

      - name: Create run folder
        run: |
          RUN_ID=${{ github.run_number }}

          mkdir -p publish/run-$RUN_ID
          cp -r allure-report/* publish/run-$RUN_ID

          mkdir -p publish/latest
          cp -r allure-report/* publish/latest

          cat <<EOF > publish/index.html
          <!DOCTYPE html>
          <html>
          <head>
          <meta http-equiv="refresh" content="0; url=latest/" />
          <title>Redirecting...</title>
          </head>
          <body>
          <p>Redirecting to latest test report...</p>
          </body>
          </html>
             EOF

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish
          publish_branch: gh-pages
          keep_files: true
          force_orphan: false